# Generated by Django 6.1 on 2026-09-05 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_account_account_holder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='')),
                ('type', models.CharField(max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('category', models.CharField(max_length=20)),
                ('sent_from', models.CharField(max_length=20)),
                ('sent_to', models.CharField(max_length=20)),
                ('note', models.CharField(max_length=100)),
                ('account_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
